#DATA
data_root: /../../Datasets/BTCV2_
classes: 14
modality: CT


#MODEL
arch: sam
in_chan: 1
base_chan: 32
conv_block: 'BasicBlock'


vit_name: 'vit_b' # 'vit_b', 'vit_l', 'vit_h'
do_ds: True
crop_size: [96, 96, 96] # Default to Task003_tumor. Task001_ACDC is [16, 160, 160]. Task002_Synapse is [64, 176, 176]
down_scale: [[2,2,2], [2,2,2], [2,2,2], [2,2,2]]
kernel_size: [[3,3,3], [3,3,3], [3,3,3], [3,3,3], [3,3,3]]
chan_num: [64, 128, 256, 320, 256, 128, 64, 32]
norm: in
act: relu
map_size: [4, 4, 4]
conv_num: [2,0,0,0, 0,0,2,2]
trans_num: [0,2,4,6, 4,2,0,0]
num_heads: [1,1,1,1, 1,1,1,1]
expansion: 4
fusion_depth: 2
fusion_dim: 320
fusion_heads: 10
attn_drop: 0.
proj_drop: 0.
proj_type: 'depthwise'


#TRAIN
epochs: 800
training_size: [96, 96, 96] # training crop size. Probably should be the same as the window size. Test with [128, 128, 128]
start_epoch: 0
num_workers: 0 ## Important
aug_device: 'cpu'

aux_loss: False
aux_weight: [0.5, 0.5]

split_seed: 0
k_fold: 5

optimizer: adamw
base_lr: 0.001 # 0.0004
betas: [0.9, 0.999]
weight_decay: 0.05  # weight decay of the optimizer
weight: [0.5, 1, 3]
rlt: 1 # relation between CE and Dice loss


scale: [0.3, 0.3, 0.3]  # scale for data augmentation
rotate: [30, 30, 30] # rotation angle for data augmentation 
translate: [0, 0, 0]
affine_pad_size: [50, 50, 50]
gaussian_noise_std: 0.02

print_freq: 5
iter_per_epoch: 500




#VALIDATION
ema: True
ema_alpha: 0.99
val_freq: 10



#INFERENCE
sliding_window: True
window_size: [96, 96, 96]


# DDP
world_size: 1
proc_idx: 0
rank: 0
port: 10000
dist_url: 'tcp://localhost:10000' # the port number here should be the same as the previous one
dist_backend: "nccl"
multiprocessing_distributed: true
reproduce_seed: null


