#DAT
data_root: /Datasets/BTCV_normalized/
classes: 14
modality: CT


#MODEL
arch: unetr
in_chan: 1
base_chan: 16
norm: in
init_model: /../model/initmodel/UNETR_model_best_acc.pth

#TRAIN
epochs: 800
training_size: [96, 96, 96] # training crop size
start_epoch: 0
num_workers: 0 ## Important 
aug_device: 'cpu'

percentage_train: 0.8


split_seed: 0
k_fold: 5

optimizer: adamw
base_lr: 0.0001
betas: [0.9, 0.999]
weight_decay: 0.00005  # weight decay of SGD optimizer
weight: [0.5, 1, 2]
rlt: 1 # relation between CE and Dice loss

scale: [0.3, 0.3, 0.3]  # scale for data augmentation  0.1 0.3 0.3
rotate: [30, 30, 30] # rotation angle for data augmentation 
translate: [0, 0, 0]
affine_pad_size: [40, 40, 40]
gaussian_noise_std: 0.02

print_freq: 5
iter_per_epoch: 500


#VALIDATION
ema: False
ema_alpha: 0.99
val_freq: 20



#INFERENCE
sliding_window: True
window_size: [96, 96, 96]


# DDP
world_size: 1
proc_idx: 0
rank: 0
port: 10000
dist_url: 'tcp://localhost:10000' # the port number here should be the same as the previous one
dist_backend: "nccl"
multiprocessing_distributed: true
reproduce_seed: null


